<?php

/**
 * @file
 * Contains references_modal.module..
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\Core\Ajax\CloseDialogCommand;

/**
 * Implements hook_form_alter().
 */
function references_modal_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
  if ($form_state->has('is_modal_form') && $form_state->get('is_modal_form')) {
    $form['#prefix'] = '<div class="references_modal_form_wrapper">';
    $form['#suffix'] = '</div>';
    $form['#attached']['library'][] = 'core/drupal.ajax';
    $form['#attached']['library'][] = 'core/drupal.dialog.ajax';

    $form['actions']['submit']['#ajax'] = [
      'callback' => 'references_modal_ajax_submit',
      'wrapper' => 'modal_dialog_form',
    ];
    $form['actions']['delete']['#access'] = FALSE;
  }
}

/**
 * Ajax callback for references modal forms.
 *
 * @param array $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 *
 * @return \Drupal\Core\Ajax\AjaxResponse
 *   An ajax response that will handle the form submission.
 */
function references_modal_ajax_submit(array $form, FormStateInterface &$form_state) {
  $response = new AjaxResponse();
  $dialog_id = '#references_modal_' . $form['#form_id'];
  if ($form_state::hasAnyErrors()) {
    $form['status_messages'] = [
      '#type' => 'status_messages',
      '#weight' => -100,
    ];
    $response->addCommand(new ReplaceCommand("$dialog_id > .references_modal_form_wrapper", $form));
  }
  else {
    $title = t('Success');
    $content = [
      'status_messages' => [
        '#type' => 'status_messages',
      ],
      'confirm' => [
        '#markup' => t('The modal form has been submitted.'),
      ],
    ];
    $options = [
      'width' => '8vm',
    ];
    $response->addCommand(new CloseDialogCommand($dialog_id));
    $response->addCommand(new OpenModalDialogCommand($title, $content, $options));
  }
  return $response;
}
